### ISSUE TITLE
screentime_* modules: "file contains parsing errors"

### ISSUE THREAD

**Issue by dmrd** [mac4n6/APOLLO#20]
Hello,

I'm having some trouble running the recently added screentime modules, as they seem to be have some errors which make the parser fail. This occurs with all of the screentime_* modules. I've included an error for the screentime_timed_items below. This is on a fresh clone of the repo with python3 on OSX.

Thanks for making APOLLO! I've been trying it out to analyze device data and it's generally been working great.

```
> python apollo.py -o csv -p apple -v 13 modules /private/var/db/CoreDuet/Knowledge/

--------------------------------------------------------------------------------------
APOLLO Version: 05072020
Platform: apple
Version: 13
Data Directory: /private/var/db/CoreDuet/Knowledge/
Modules Directory: modules
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "apollo.py", line 259, in <module>
    parse_module_definition(mod_info)
  File "apollo.py", line 56, in parse_module_definition
    parser.read(mod_def)
  File "/usr/local/anaconda3/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/anaconda3/lib/python3.7/configparser.py", line 1110, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'modules/screentime_timed_items.txt'
	[line 64]: '\tSELECT \n'
	[line 65]: "\t\tDATETIME(ZUSAGEBLOCK.ZSTARTDATE+978307200,'UNIXEPOCH') AS 'HOUR',\n"
	[line 66]: "\t\tZUSAGETIMEDITEM.ZBUNDLEIDENTIFIER AS  'BUNDLE ID',\n"
... [until line 95]
```

**Comment by mac4n6** [comment]
Those modules had a minor error that has now been fixed, re-download those and give it another go!
